version: "2"
services:
#  files_creator:
#    build:
#      context: .
#      dockerfile: files_creator/Dockerfile
#    container_name: files_creator
#    ports:
#    - 8800:8081
#    restart: always
#    volumes:
#    - .:/go/src/github.com/anupam0601/golang-stuff/ints-perf-automation

  filescreatormicro:
    build:
      context: .
      dockerfile: filescreatormicro/Dockerfile
    container_name: filescreatormicro
    ports:
      - 8080:8080
    restart: always
    volumes:
      - .:/go/src/github.com/anupam0601/golang-stuff/ints-perf-automation
